language: elixir
elixir:
  - 1.3.4
  - 1.4.5
  - 1.5.2
  - 1.6.0-rc.0
otp_release:
  - 18.3
  - 19.3
  - 20.0
matrix:
  exclude:
    - elixir: 1.3.4
      otp_release: 20.0

before_script:
  - MIX_ENV=test mix compile --warnings-as-errors
  - travis_wait mix dialyzer --plt
script:
  - mix credo --strict
  - # skip dialyzer for elixir 1.4 and erlang 18 as it produces weird errors, see #69
  - if ! ([[ "$TRAVIS_ELIXIR_VERSION" == "1.4"* ]] && [[ "$TRAVIS_OTP_RELEASE" == "18"* ]]); then mix dialyzer --halt-exit-status; fi
  - mix safe_coveralls.travis
after_script:
  - mix deps.get --only docs
  - MIX_ENV=docs mix inch.report
sudo: required
dist: trusty
cache:
  directories:
    - _build
    - deps
