language: elixir
elixir:
  - 1.6.6
  - 1.7.4
  - 1.8.2
  - 1.9.4
  - 1.10.0
otp_release:
  - 20.3
  - 21.3
  - 22.2
matrix:
  include:
    - elixir: 1.6.6
      otp_release: 19.3
  exclude:
    - elixir: 1.6.6
      otp_release: 22.2
    - elixir: 1.10.0
      otp_release: 20.3
before_script:
  - MIX_ENV=test mix compile --warnings-as-errors
  - travis_wait mix dialyzer --plt
script:
  - mix credo --strict
  - if [[ "$TRAVIS_ELIXIR_VERSION" == "1.10"* ]]; then mix format --check-formatted; fi
  - mix dialyzer --halt-exit-status
  - mix coveralls.travis
after_script:
  - if [[ "$TRAVIS_ELIXIR_VERSION" == "1.10"* ]]; then mix deps.get --only docs && MIX_ENV=docs mix inch.report; fi
sudo: required
dist: trusty
cache:
  directories:
    - _build
    - deps
