version: build{build}

install:
  # current elixir install breaks see https://ci.appveyor.com/project/PragTob/benchee-8e4gw/builds/32804950
  - cinst elixir --version 1.10.3
  - refreshenv

shallow_clone: true

build_script:
  - mix local.hex --force
  - mix deps.get
  - mix local.rebar --force
  - mix compile --warnings-as-errors

test_script:
  - mix test
